"""Furniture type catalog for the ACNH reference db (two levels).

Every furniture item gets:
  - broad   type (Kitchen, Decoration, Furniture, Lighting, ...) — the parent group
  - specific type (Cup, Guitar, Chair, Table, ...)                — the discrete item kind

Single source of truth: build_db.py imports classify() and writes items.type /
items.subtype during every build, so the catalog survives rebuilds.

Mechanisms, applied in order:
  1. KEYWORD_RULES — substring match on the lowercased name (first hit wins).
  2. OVERRIDES     — explicit name -> (broad, specific) for items the rules miss.
Anything still unmatched after both -> ("Other", "Other").

Run:  python3 scripts/furniture_types.py   # writes res/furniture_types.tsv + coverage report
"""

FURNITURE_CATEGORIES = [
    "Housewares", "Miscellaneous", "Wall-mounted", "Ceiling Decor",
    "Interior Structures",
]

# name -> (broad, specific) for items the keyword rules miss or misclassify.
# Keys are matched case-insensitively (lowercased at load).
OVERRIDES = {
    # ---- Seating (normalize broad to Furniture) ----
    "crew member's seat": ("Furniture", "Seat"),
    "golden seat": ("Furniture", "Seat"),
    "transit seat": ("Furniture", "Seat"),
    "ruined seat": ("Furniture", "Seat"),
    # ---- Storage (normalize broad to Furniture) ----
    "Nordic shelves": ("Furniture", "Shelf"),
    "Pompompurin rack": ("Furniture", "Rack"),
    "artful shelves": ("Furniture", "Shelf"),
    "corner clothing rack": ("Furniture", "Rack"),
    "drying rack": ("Furniture", "Rack"),
    "effects rack": ("Furniture", "Rack"),
    "hanger rack": ("Furniture", "Rack"),
    "large magazine rack": ("Furniture", "Rack"),
    "magazine rack": ("Furniture", "Rack"),
    "midsized clothing rack": ("Furniture", "Rack"),
    "open wooden shelves": ("Furniture", "Shelf"),
    "plastic clothing organizer": ("Furniture", "Organizer"),
    "rescue mannequin": ("Furniture", "Mannequin"),
    "small clothing rack": ("Furniture", "Rack"),
    "small mannequin": ("Furniture", "Mannequin"),
    "tension-pole rack": ("Furniture", "Rack"),
    "tubular magazine rack": ("Furniture", "Rack"),
    "tubular shelves": ("Furniture", "Shelf"),
    "upright organizer": ("Furniture", "Organizer"),
    "glass showcase": ("Furniture", "Display"),
    "dessert case": ("Furniture", "Display"),
    "ice-cream display": ("Furniture", "Display"),
    "ice cream display": ("Furniture", "Display"),
    "retro ice-cream case": ("Furniture", "Display"),
    "ice-cream set": ("Kitchen", "Food"),
    "dress mannequin": ("Furniture", "Mannequin"),
    "imperial decorative shelves": ("Furniture", "Shelf"),
    "ski rack": ("Furniture", "Rack"),
    "clothes closet": ("Furniture", "Storage"),
    "changing room": ("Furniture", "Storage"),
    "dressing room": ("Furniture", "Storage"),
    "stepladder": ("Furniture", "Ladder"),
    "horizontal organizer": ("Furniture", "Organizer"),
    # ---- Electronics / appliances ----
    "ABD": ("Electronics", "Appliance"),
    "ACNH Nintendo Switch": ("Electronics", "Game Console"),
    "air circulator": ("Electronics", "Fan"),
    "amp": ("Electronics", "Amplifier"),
    "brake tapper": ("Toy", "Arcade"),
    "candy-skull music player": ("Electronics", "Music Player"),
    "cassette player": ("Electronics", "Music Player"),
    "chainsaw": ("Electronics", "Power Tool"),
    "confetti machine": ("Electronics", "Machine"),
    "copy machine": ("Electronics", "Office"),
    "cordless phone": ("Electronics", "Phone"),
    "digital scale": ("Kitchen", "Scale"),
    "DJ cap": ("Clothing", "Hat"),
    "drink machine": ("Electronics", "Machine"),
    "EKG machine": ("Electronics", "Medical"),
    "electronics kit": ("Electronics", "Kit"),
    "extinguisher": ("Electronics", "Safety"),
    "fax machine": ("Electronics", "Office"),
    "Festivale confetti machine": ("Electronics", "Machine"),
    "frozen-drink machine": ("Electronics", "Machine"),
    "intercom monitor": ("Electronics", "Intercom"),
    "karaoke system": ("Electronics", "Music Player"),
    "light switch": ("Electronics", "Switch"),
    "Love Tester": ("Electronics", "Machine"),
    "microscope": ("Electronics", "Lab"),
    "NES": ("Electronics", "Game Console"),
    "Newton's cradle": ("Decoration", "Desk Toy"),
    "old sewing machine": ("Electronics", "Machine"),
    "outdoor air conditioner": ("Electronics", "Air Conditioner"),
    "outdoor generator": ("Electronics", "Generator"),
    "phonograph": ("Electronics", "Music Player"),
    "portable radio": ("Electronics", "Radio"),
    "portable record player": ("Electronics", "Music Player"),
    "pro tape recorder": ("Electronics", "Recorder"),
    "projection screen": ("Electronics", "Screen"),
    "retro radiator": ("Electronics", "Heater"),
    "retro stereo": ("Electronics", "Stereo"),
    "round space heater": ("Electronics", "Heater"),
    "science pod": ("Electronics", "Lab"),
    "security camera": ("Electronics", "Camera"),
    "server": ("Electronics", "Computer"),
    "sewing machine": ("Electronics", "Machine"),
    "shaved-ice maker": ("Kitchen", "Machine"),
    "skull radio": ("Electronics", "Radio"),
    "small LED display": ("Electronics", "Screen"),
    "snack machine": ("Electronics", "Machine"),
    "solar panel": ("Electronics", "Solar"),
    "space heater": ("Electronics", "Heater"),
    "standing space heater": ("Electronics", "Heater"),
    "surveillance camera": ("Electronics", "Camera"),
    "switch": ("Electronics", "Game Console"),
    "tangled cords": ("Decoration", "Desk"),
    "tape deck": ("Electronics", "Music Player"),
    "telescope": ("Electronics", "Telescope"),
    "theremin": ("Instrument", "Theremin"),
    "tourist telescope": ("Outdoor", "Telescope"),
    "typewriter": ("Electronics", "Office"),
    "unknown machine": ("Electronics", "Machine"),
    "winnowing machine": ("Electronics", "Machine"),
    "vacuum cleaner": ("Bathroom", "Vacuum"),
    "upright vacuum": ("Bathroom", "Vacuum"),
    "washing machine": ("Bathroom", "Washer"),
    "deluxe washer": ("Bathroom", "Washer"),
    "automatic washer": ("Bathroom", "Washer"),
    "dryer": ("Bathroom", "Dryer"),
    "pants press": ("Bathroom", "Ironing"),
    "ironing board": ("Bathroom", "Ironing"),
    "ironing set": ("Bathroom", "Ironing"),
    "vacuum": ("Bathroom", "Vacuum"),
    # ---- Kitchen: food / drink / ware ----
    "aji fry": ("Kitchen", "Food"),
    "anchoas al ajillo": ("Kitchen", "Food"),
    "apple jelly": ("Kitchen", "Food"),
    "apple smoothie": ("Kitchen", "Drink"),
    "apple tart": ("Kitchen", "Food"),
    "berliner": ("Kitchen", "Food"),
    "biryani": ("Kitchen", "Food"),
    "cacao": ("Kitchen", "Food"),
    "candy": ("Kitchen", "Candy"),
    "cans": ("Kitchen", "Drink"),
    "caprese sandwich set": ("Kitchen", "Food"),
    "cherry jelly": ("Kitchen", "Food"),
    "cherry smoothie": ("Kitchen", "Drink"),
    "cherry tart": ("Kitchen", "Food"),
    "clam chowder": ("Kitchen", "Food"),
    "classic pitcher": ("Kitchen", "Pitcher"),
    "coconut cookies": ("Kitchen", "Food"),
    "coconut milk": ("Kitchen", "Drink"),
    "coconut oil": ("Kitchen", "Food"),
    "coconut pudding": ("Kitchen", "Food"),
    "cookie": ("Kitchen", "Food"),
    "cookies": ("Kitchen", "Food"),
    "cupcake": ("Kitchen", "Food"),
    "cutlery": ("Kitchen", "Cutlery"),
    "dango": ("Kitchen", "Food"),
    "deep fryer": ("Kitchen", "Appliance"),
    "double Gloucester cheese": ("Kitchen", "Food"),
    "fried rice": ("Kitchen", "Food"),
    "frosted cookies": ("Kitchen", "Food"),
    "frosted pretzels": ("Kitchen", "Food"),
    "fruit scones": ("Kitchen", "Food"),
    "gnocchi di patate": ("Kitchen", "Food"),
    "gnocchi di zucca": ("Kitchen", "Food"),
    "gratin": ("Kitchen", "Food"),
    "iced caffè latte": ("Kitchen", "Drink"),
    "iced lemon tea": ("Kitchen", "Drink"),
    "kabu ankake": ("Kitchen", "Food"),
    "karei no nitsuke": ("Kitchen", "Food"),
    "ketchup fried rice": ("Kitchen", "Food"),
    "melon soda": ("Kitchen", "Drink"),
    "milkshake": ("Kitchen", "Drink"),
    "mixed-fruits crepe": ("Kitchen", "Food"),
    "mixed-fruits sandwich": ("Kitchen", "Food"),
    "mixed-fruits tart": ("Kitchen", "Food"),
    "mushroom crepe": ("Kitchen", "Food"),
    "nanakusa gayu": ("Kitchen", "Food"),
    "nigirizushi": ("Kitchen", "Food"),
    "olive-flounder meunière": ("Kitchen", "Food"),
    "omurice": ("Kitchen", "Food"),
    "orange jelly": ("Kitchen", "Food"),
    "orange marmalade": ("Kitchen", "Food"),
    "orange smoothie": ("Kitchen", "Drink"),
    "orange tart": ("Kitchen", "Food"),
    "osechi": ("Kitchen", "Food"),
    "pad krapow": ("Kitchen", "Food"),
    "peach jelly": ("Kitchen", "Food"),
    "peach smoothie": ("Kitchen", "Drink"),
    "peach tart": ("Kitchen", "Food"),
    "pear jelly": ("Kitchen", "Food"),
    "pear smoothie": ("Kitchen", "Drink"),
    "pear tart": ("Kitchen", "Food"),
    "pesce all'acqua pazza": ("Kitchen", "Food"),
    "pickled veggies": ("Kitchen", "Food"),
    "pilaf": ("Kitchen", "Food"),
    "plain scones": ("Kitchen", "Food"),
    "poke": ("Kitchen", "Food"),
    "popcorn machine": ("Kitchen", "Machine"),
    "premium nigirizushi": ("Kitchen", "Food"),
    "pretzels": ("Kitchen", "Food"),
    "pumpkin scones": ("Kitchen", "Food"),
    "range hood": ("Kitchen", "Appliance"),
    "risotto": ("Kitchen", "Food"),
    "salmon sandwich": ("Kitchen", "Food"),
    "sardines in oil": ("Kitchen", "Food"),
    "sautéed olive flounder": ("Kitchen", "Food"),
    "spaghetti genovese": ("Kitchen", "Food"),
    "spaghetti marinara": ("Kitchen", "Food"),
    "spaghetti napolitan": ("Kitchen", "Food"),
    "spaghetti peperoncino": ("Kitchen", "Food"),
    "spooky cookies": ("Kitchen", "Food"),
    "squid-ink spaghetti": ("Kitchen", "Food"),
    "strawberry soda": ("Kitchen", "Drink"),
    "sugar crepe": ("Kitchen", "Food"),
    "super-premium nigirizushi": ("Kitchen", "Food"),
    "surichwi tteok": ("Kitchen", "Food"),
    "tangyuan": ("Kitchen", "Food"),
    "veggie cookies": ("Kitchen", "Food"),
    "veggie crepe": ("Kitchen", "Food"),
    "veggie quiche": ("Kitchen", "Food"),
    "veggie sandwich": ("Kitchen", "Food"),
    "veggie sandwich set": ("Kitchen", "Food"),
    "yule log": ("Kitchen", "Food"),
    "Roost sablé cookie": ("Kitchen", "Food"),
    "chocolate heart": ("Kitchen", "Food"),
    "cheese wheel": ("Kitchen", "Food"),
    "cupcake": ("Kitchen", "Food"),
    "orange": ("Kitchen", "Food"),
    "peach": ("Kitchen", "Food"),
    "egg": ("Kitchen", "Food"),
    "champagne": ("Kitchen", "Drink"),
    "coconut water": ("Kitchen", "Drink"),
    "coconut juice": ("Kitchen", "Drink"),
    "kiwi juice": ("Kitchen", "Drink"),
    "orange juice": ("Kitchen", "Drink"),
    "ice cream": ("Kitchen", "Food"),
    "ice-cream cone": ("Kitchen", "Food"),
    "french fries": ("Kitchen", "Food"),
    "hotdog": ("Kitchen", "Food"),
    "mushroom curry": ("Kitchen", "Food"),
    "mushroom pizza": ("Kitchen", "Food"),
    "mushroom salad": ("Kitchen", "Food"),
    "pasta": ("Kitchen", "Food"),
    "pizza": ("Kitchen", "Food"),
    "ramen": ("Kitchen", "Food"),
    "salad": ("Kitchen", "Food"),
    "seafood salad": ("Kitchen", "Food"),
    "soup kettle": ("Kitchen", "Cookware"),
    "Turkey Day casserole": ("Kitchen", "Food"),
    "pound cake": ("Kitchen", "Food"),
    "shredded wheat": ("Kitchen", "Food"),
    "fruit basket": ("Kitchen", "Food"),
    "milk": ("Kitchen", "Drink"),
    "infused-water dispenser": ("Kitchen", "Dispenser"),
    # ---- Instruments ----
    "clarinet": ("Decoration", "Instrument"),
    "keyboard": ("Instrument", "Keyboard"),
    "theremin": ("Instrument", "Theremin"),
    "wedding pipe organ": ("Decoration", "Instrument"),
    "recycled-can thumb piano": ("Instrument", "Piano"),
    # ---- Decoration ----
    "1-Up Mushroom": ("Decoration", "Figurine"),
    "Capricorn ornament": ("Decoration", "Figurine"),
    "Casablanca lilies": ("Plant", "Flower"),
    "Cinnamoroll tray": ("Kitchen", "Tray"),
    "Decayed Guardian": ("Decoration", "Figurine"),
    "Festivale float": ("Outdoor", "Float"),
    "Festivale parasol": ("Umbrella", "Parasol"),
    "Festivale stage": ("Outdoor", "Stage"),
    "Festivale stall": ("Outdoor", "Stall"),
    "Goal Pole": ("Outdoor", "Sports"),
    "Golden Egg": ("Decoration", "Figurine"),
    "Heart Container": ("Decoration", "Figurine"),
    "IV drip": ("Decoration", "Medical"),
    "Jack's portrait": ("Decoration", "Art"),
    "Kerokerokeroppi bridge": ("Outdoor", "Bridge"),
    "Kerokerokeroppi hallway": ("Wall Decor", "Arch"),
    "Kerokerokeroppi snack": ("Kitchen", "Food"),
    "Kerokerokeroppi tray": ("Kitchen", "Tray"),
    "Kiki & Lala cloud maker": ("Decoration", "Figurine"),
    "LEGO® fireplace": ("Toy", "Figurine"),
    "LEGO® plum blossom": ("Toy", "Figurine"),
    "Libra scale": ("Decoration", "Figurine"),
    "Lunar New Year decoration": ("Decoration", "Figurine"),
    "Master Sword": ("Decoration", "Weapon"),
    "Mom's art": ("Decoration", "Art"),
    "Mom's cushion": ("Decoration", "Cushion"),
    "Mom's embroidery": ("Decoration", "Art"),
    "Mom's tea cozy": ("Kitchen", "Tea"),
    "Moroccan footrest": ("Furniture", "Ottoman"),
    "Mr. Flamingo": ("Decoration", "Figurine"),
    "Mrs. Flamingo": ("Decoration", "Figurine"),
    "New Year's noodles": ("Kitchen", "Food"),
    "New Year's shimekazari": ("Decoration", "Decor"),
    "Nook Inc. cushion": ("Decoration", "Cushion"),
    "Paradise Planning cushion": ("Decoration", "Cushion"),
    "Paradise Planning photo": ("Decoration", "Photo"),
    "Paradise Planning tissues": ("Bathroom", "Tissues"),
    "Pompompurin pudding": ("Kitchen", "Food"),
    "RC helicopter": ("Toy", "Vehicle"),
    "Ring-Con": ("Toy", "Game"),
    "Rover's briefcase": ("Container", "Bag"),
    "Sagittarius arrow": ("Decoration", "Figurine"),
    "Shell": ("Decoration", "Figurine"),
    "South Pole": ("Decoration", "Figurine"),
    "Splattershot": ("Decoration", "Weapon"),
    "Super Mushroom": ("Decoration", "Figurine"),
    "Super NES (NTSC version)": ("Electronics", "Game Console"),
    "Super NES (PAL version)": ("Electronics", "Game Console"),
    "Super Sea Snail": ("Decoration", "Figurine"),
    "Super Star": ("Decoration", "Figurine"),
    "Thwomp": ("Decoration", "Figurine"),
    "Tower of Pisa": ("Decoration", "Figurine"),
    "Triforce": ("Decoration", "Figurine"),
    "Turkey Day decorations": ("Decoration", "Decor"),
    "Turkey Day hearth": ("Decoration", "Hearth"),
    "Turkey Day wheat decor": ("Decoration", "Decor"),
    "Ultra Hand": ("Toy", "Game"),
    "Ultra Machine": ("Toy", "Game"),
    "Yut Nori": ("Toy", "Game"),
    "Zonai authentication crest": ("Decoration", "Figurine"),
    # ---- Furniture ----
    "aluminum briefcase": ("Container", "Bag"),
    "amazing machine": ("Decoration", "Machine"),
    "art plaque": ("Decoration", "Plaque"),
    "asteroid": ("Decoration", "Figurine"),
    "azumaya gazebo": ("Outdoor", "Gazebo"),
    "bamboo grass": ("Plant", "Grass"),
    "bamboo sphere": ("Decoration", "Sphere"),
    "baobab": ("Plant", "Tree"),
    "blue corner": ("Outdoor", "Sports"),
    "bonfire": ("Outdoor", "Fire"),
    "boomerang": ("Toy", "Toy"),
    "bow": ("Decoration", "Weapon"),
    "breaker": ("Electronics", "Safety"),
    "brick pillar": ("Furniture", "Pillar"),
    "bronze HHA plaque": ("Decoration", "Plaque"),
    "bulldozer": ("Toy", "Vehicle"),
    "busing station": ("Outdoor", "Station"),
    "castle tower": ("Outdoor", "Tower"),
    "cat grass": ("Plant", "Grass"),
    "cat tower": ("Pet", "Cat Furniture"),
    "cave": ("Decoration", "Cave"),
    "cherry-blossom branches": ("Wall Decor", "Branches"),
    "circle cushion": ("Decoration", "Cushion"),
    "clothesline pole": ("Outdoor", "Clothesline"),
    "coin": ("Decoration", "Coin"),
    "colorful wheel": ("Toy", "Game"),
    "concrete pillar": ("Furniture", "Pillar"),
    "construction scaffolding": ("Outdoor", "Scaffolding"),
    "conveyor belt": ("Electronics", "Machine"),
    "cool globe": ("Decoration", "Globe"),
    "covered wagon": ("Outdoor", "Wagon"),
    "crewed spaceship": ("Toy", "Vehicle"),
    "decorative pillar": ("Furniture", "Pillar"),
    "decoy duck": ("Decoration", "Figurine"),
    "deer decoration": ("Decoration", "Figurine"),
    "die": ("Toy", "Game"),
    "dispenser": ("Kitchen", "Dispenser"),
    "evergreen ash": ("Plant", "Tree"),
    "excavator": ("Toy", "Vehicle"),
    "fax machine": ("Electronics", "Office"),
    "fine vase": ("Decoration", "Vase"),
    "first-aid kit": ("Bathroom", "First Aid"),
    "floral sconce": ("Wall Decor", "Sconce"),
    "floral swag": ("Wall Decor", "Swag"),
    "flying saucer": ("Decoration", "Figurine"),
    "forbidden altar": ("Decoration", "Altar"),
    "forsythia": ("Plant", "Flower"),
    "fortune-telling set": ("Decoration", "Fortune"),
    "fossil plaque": ("Decoration", "Plaque"),
    "fragrance sticks": ("Decoration", "Fragrance"),
    "frozen mini snowperson": ("Decoration", "Figurine"),
    "frozen pillar": ("Furniture", "Pillar"),
    "frozen-treat set": ("Kitchen", "Food"),
    "gazebo": ("Outdoor", "Gazebo"),
    "gear apparatus": ("Decoration", "Gear"),
    "gear tower": ("Decoration", "Gear"),
    "glow-in-the-dark stickers": ("Wall Decor", "Stickers"),
    "glowing-moss boulder": ("Outdoor", "Rock"),
    "glowing-moss pond": ("Outdoor", "Pond"),
    "gold HHA plaque": ("Decoration", "Plaque"),
    "golden casket": ("Furniture", "Storage"),
    "golden dharma": ("Decoration", "Figurine"),
    "golden gear apparatus": ("Decoration", "Gear"),
    "golden gear tower": ("Decoration", "Gear"),
    "golden meter and pipes": ("Decoration", "Pipes"),
    "golden pillar": ("Furniture", "Pillar"),
    "golden samurai suit": ("Decoration", "Armor"),
    "golden wristwatch": ("Decoration", "Watch"),
    "green-leaf pile": ("Outdoor", "Leaf Pile"),
    "handwashing area": ("Bathroom", "Sink"),
    "heart": ("Decoration", "Heart"),
    "hinaningyo": ("Decoration", "Figurine"),
    "homework set": ("Decoration", "Study"),
    "horizontal split curtains": ("Wall Decor", "Curtains"),
    "horseshoe door decoration": ("Decoration", "Decor"),
    "hotel snow globe": ("Decoration", "Globe"),
    "ice pail": ("Container", "Bucket"),
    "illuminated present": ("Decoration", "Decor"),
    "illuminated reindeer": ("Decoration", "Decor"),
    "illuminated snowflakes": ("Decoration", "Decor"),
    "inspection equipment": ("Electronics", "Equipment"),
    "jackhammer": ("Electronics", "Power Tool"),
    "judge's bell": ("Decoration", "Bell"),
    "kagamimochi": ("Decoration", "Decor"),
    "katana": ("Decoration", "Weapon"),
    "key holder": ("Decoration", "Holder"),
    "key tray": ("Decoration", "Tray"),
    "kiddie house": ("Toy", "Playground"),
    "kiddie seesaw": ("Toy", "Playground"),
    "kiddie slide": ("Toy", "Playground"),
    "large Mushroom Platform": ("Furniture", "Platform"),
    "log stakes": ("Outdoor", "Stakes"),
    "loom": ("Decoration", "Craft"),
    "lucky cat": ("Decoration", "Figurine"),
    "lucky gold cat": ("Decoration", "Figurine"),
    "lunar lander": ("Toy", "Vehicle"),
    "lunar rover": ("Toy", "Vehicle"),
    "magazine": ("Decoration", "Magazine"),
    "magic kit": ("Toy", "Game"),
    "makeup pouch": ("Bathroom", "Makeup"),
    "manhole cover": ("Outdoor", "Cover"),
    "marigold decoration": ("Decoration", "Decor"),
    "maypole": ("Outdoor", "Maypole"),
    "medieval building side": ("Outdoor", "Building"),
    "metal can": ("Container", "Can"),
    "meter and pipes": ("Decoration", "Pipes"),
    "milk can": ("Container", "Can"),
    "mini golden dharma": ("Decoration", "Figurine"),
    "mochi pestle": ("Kitchen", "Kitchenware"),
    "modern cash register": ("Kitchen", "Register"),
    "mop": ("Bathroom", "Cleaning"),
    "mounted black bass": ("Decoration", "Mounted Display"),
    "mounted blue marlin": ("Decoration", "Mounted Display"),
    "neutral corner": ("Outdoor", "Sports"),
    "nuptial bell": ("Decoration", "Bell"),
    "nuptial ring pillow": ("Decoration", "Cushion"),
    "old-fashioned washtub": ("Bathroom", "Washbasin"),
    "ornithopter": ("Toy", "Toy"),
    "pagoda": ("Outdoor", "Pagoda"),
    "paint cans": ("Container", "Can"),
    "pergola": ("Outdoor", "Pergola"),
    "pile of cash": ("Decoration", "Cash"),
    "pile of leaves": ("Outdoor", "Leaf Pile"),
    "pile of zen cushions": ("Decoration", "Cushion"),
    "pipe": ("Furniture", "Pipe"),
    "pirate-ship cannon": ("Decoration", "Cannon"),
    "pirate-ship helm": ("Decoration", "Helm"),
    "plaza ferris wheel": ("Toy", "Playground"),
    "plaza merry-go-round": ("Toy", "Playground"),
    "pop-up book": ("Toy", "Book"),
    "porcelain vase": ("Decoration", "Vase"),
    "powder-room booth": ("Bathroom", "Booth"),
    "raccoon figurine": ("Decoration", "Figurine"),
    "recycled-paper bundle": ("Container", "Bundle"),
    "red corner": ("Outdoor", "Sports"),
    "red-leaf pile": ("Outdoor", "Leaf Pile"),
    "retro transportation stop": ("Outdoor", "Station"),
    "ring": ("Decoration", "Ring"),
    "ringtoss": ("Toy", "Game"),
    "rodeo-style springy ride-on": ("Toy", "Ride"),
    "rolling suitcase": ("Container", "Bag"),
    "round pillow": ("Decoration", "Cushion"),
    "ruined broken pillar": ("Furniture", "Pillar"),
    "ruined decorated pillar": ("Furniture", "Pillar"),
    "rupee": ("Decoration", "Coin"),
    "satellite": ("Decoration", "Figurine"),
    "scattered papers": ("Decoration", "Papers"),
    "schefflera": ("Plant", "Plant"),
    "scrapbook": ("Decoration", "Book"),
    "sea globe": ("Decoration", "Globe"),
    "set of stockings": ("Wall Decor", "Stockings"),
    "sewing project": ("Decoration", "Craft"),
    "ship-wheel door decoration": ("Wall Decor", "Wheel"),
    "shoji divider": ("Wall Decor", "Screen"),
    "silent princess": ("Decoration", "Figurine"),
    "silo": ("Outdoor", "Silo"),
    "silver HHA plaque": ("Decoration", "Plaque"),
    "silver confetti blower": ("Toy", "Toy"),
    "simple pillar": ("Furniture", "Pillar"),
    "siren": ("Outdoor", "Siren"),
    "sleigh": ("Outdoor", "Sleigh"),
    "small Mushroom Platform": ("Furniture", "Platform"),
    "small vase": ("Decoration", "Vase"),
    "soccer goal": ("Outdoor", "Sports"),
    "space shuttle": ("Toy", "Vehicle"),
    "sphinx": ("Decoration", "Figurine"),
    "spider web": ("Decoration", "Decor"),
    "spooky tower": ("Decoration", "Tower"),
    "springy ride-on": ("Toy", "Ride"),
    "squid bumper": ("Decoration", "Figurine"),
    "stack of books": ("Decoration", "Books"),
    "stack of clothes": ("Furniture", "Storage"),
    "stage flame machine": ("Electronics", "Machine"),
    "steel pillar": ("Furniture", "Pillar"),
    "storage shed": ("Outdoor", "Shed"),
    "storefront": ("Outdoor", "Storefront"),
    "strapped books": ("Decoration", "Books"),
    "stroller": ("Toy", "Stroller"),
    "suspicious cauldron": ("Decoration", "Cauldron"),
    "sword": ("Decoration", "Weapon"),
    "termite mound": ("Decoration", "Mound"),
    "terrarium": ("Plant", "Terrarium"),
    "three-tiered snowperson": ("Decoration", "Figurine"),
    "throne": ("Furniture", "Chair"),
    "throwback container": ("Container", "Container"),
    "tire stack": ("Outdoor", "Tire"),
    "titan arum": ("Plant", "Flower"),
    "tokonoma": ("Wall Decor", "Tokonoma"),
    "torii": ("Outdoor", "Gate"),
    "tractor": ("Toy", "Vehicle"),
    "truck": ("Toy", "Vehicle"),
    "unfolded reference sheet": ("Decoration", "Paper"),
    "utility pole": ("Outdoor", "Pole"),
    "utility wagon": ("Container", "Wagon"),
    "vertical banner": ("Wall Decor", "Banner"),
    "vertical split curtains": ("Wall Decor", "Curtains"),
    "washbasin": ("Bathroom", "Sink"),
    "wave breaker": ("Outdoor", "Breakwater"),
    "wedding decoration": ("Decoration", "Decor"),
    "wheat field": ("Plant", "Wheat"),
    "whoopee cushion": ("Toy", "Toy"),
    "wooden pillar": ("Furniture", "Pillar"),
    "wooden storage shed": ("Outdoor", "Shed"),
    "world map": ("Wall Decor", "Map"),
    "wristwatch": ("Decoration", "Watch"),
    "yacht": ("Toy", "Vehicle"),
    "yellow-leaf pile": ("Outdoor", "Leaf Pile"),
    "yucca": ("Plant", "Plant"),
    "zodiac boar figurine": ("Decoration", "Figurine"),
    "zodiac dog figurine": ("Decoration", "Figurine"),
    "zodiac dragon figurine": ("Decoration", "Figurine"),
    "zodiac horse figurine": ("Decoration", "Figurine"),
    "zodiac monkey figurine": ("Decoration", "Figurine"),
    "zodiac ox figurine": ("Decoration", "Figurine"),
    "zodiac pig figurine": ("Decoration", "Figurine"),
    "zodiac rabbit figurine": ("Decoration", "Figurine"),
    "zodiac rat figurine": ("Decoration", "Figurine"),
    "zodiac rooster figurine": ("Decoration", "Figurine"),
    "zodiac sheep figurine": ("Decoration", "Figurine"),
    "zodiac snake figurine": ("Decoration", "Figurine"),
    "zodiac tiger figurine": ("Decoration", "Figurine"),
}

# Stragglers re-added after a file-editing mishap (see git history / TSV review).
OVERRIDES.update({
    "clothesline": ("Outdoor", "Clothesline"),
    "cold sleep pod": ("Furniture", "Pod"),
    "cone": ("Outdoor", "Cone"),
    "cornucopia": ("Decoration", "Cornucopia"),
    "cucumber horse": ("Decoration", "Figurine"),
    "cushion": ("Decoration", "Cushion"),
    "decorative bottles": ("Decoration", "Bottles"),
    "dharma": ("Decoration", "Figurine"),
    "document stack": ("Decoration", "Papers"),
    "doghouse": ("Outdoor", "Doghouse"),
    "double-edged sword": ("Decoration", "Weapon"),
    "drapery": ("Wall Decor", "Curtains"),
    "dreamy shelves": ("Furniture", "Shelf"),
    "electric bass": ("Decoration", "Instrument"),
    "essay set": ("Decoration", "Study"),
    "fairy bottle": ("Decoration", "Bottle"),
    "festive top set": ("Decoration", "Decor"),
    "fire pit": ("Outdoor", "Fire"),
    "fireplace": ("Decoration", "Fireplace"),
    "firewood": ("Outdoor", "Firewood"),
    "formal paper": ("Decoration", "Paper"),
    "fragrance diffuser": ("Decoration", "Fragrance"),
    "gears": ("Decoration", "Gear"),
    "gift pile": ("Decoration", "Decor"),
    "globe": ("Decoration", "Globe"),
    "gold bars": ("Decoration", "Gold"),
    "golden altar": ("Decoration", "Altar"),
    "golden dung beetle": ("Decoration", "Figurine"),
    "golden gears": ("Decoration", "Gear"),
    "golden piggy bank": ("Furniture", "Storage"),
    "golden vase": ("Decoration", "Vase"),
    "heart-shaped bouquet": ("Decoration", "Bouquet"),
    "hearth": ("Decoration", "Hearth"),
    "hose reel": ("Outdoor", "Hose"),
    "humidifier": ("Bathroom", "Humidifier"),
    "jail bars": ("Outdoor", "Bars"),
    "lab-experiments set": ("Decoration", "Lab"),
    "lawn mower": ("Outdoor", "Lawn Mower"),
    "life ring": ("Outdoor", "Life Ring"),
    "log decorative shelves": ("Furniture", "Shelf"),
    "marble fireplace": ("Decoration", "Fireplace"),
    "metronome": ("Decoration", "Instrument"),
    "mini circuit": ("Toy", "Game"),
    "mini dharma": ("Decoration", "Figurine"),
    "moon": ("Decoration", "Moon"),
    "mush log": ("Decoration", "Log"),
    "mush parasol": ("Decoration", "Parasol"),
    "nail-art set": ("Bathroom", "Makeup"),
    "painting set": ("Decoration", "Craft"),
    "paper tiger": ("Decoration", "Figurine"),
    "piggy bank": ("Furniture", "Storage"),
    "protein shaker bottle": ("Kitchen", "Bottle"),
    "retro gas pump": ("Outdoor", "Gas Pump"),
    "salad bar": ("Kitchen", "Counter"),
    "samurai suit": ("Decoration", "Armor"),
    "snow globe": ("Decoration", "Globe"),
    "spray can": ("Decoration", "Spray"),
    "stacked magazines": ("Decoration", "Magazines"),
    "stadiometer": ("Bathroom", "Scale"),
    "stall": ("Outdoor", "Stall"),
    "steamroller": ("Toy", "Vehicle"),
    "tiny library": ("Furniture", "Storage"),
    "windmill": ("Outdoor", "Windmill"),
    "zen cushion": ("Decoration", "Cushion"),
    "cooking tools": ("Kitchen", "Cookware"),
    "cream and sugar": ("Kitchen", "Kitchenware"),
    "dinnerware": ("Kitchen", "Plates"),
    "tea set": ("Kitchen", "Tea"),
    "traditional tea set": ("Kitchen", "Tea"),
    "siphon": ("Decoration", "Siphon"),
    "smoker": ("Outdoor", "Smoker"),
    "gas range": ("Kitchen", "Appliance"),
    "spinning wheel": ("Decoration", "Craft"),
    "mush": ("Decoration", "Mushroom"),
    "coffee cup": ("Kitchen", "Cups"),
    "analog kitchen scale": ("Kitchen", "Scale"),
    "royal coffee cup": ("Kitchen", "Cups"),
    "cage cup": ("Kitchen", "Cups"),
    "glass holder with candle": ("Lighting", "Candle"),
    "glass candle with holder": ("Lighting", "Candle"),

    "Cinnamoroll parasol": ("Umbrella", "Parasol"),
    "Dala horse": ("Decoration", "Figurine"),
    "Market Place decoration": ("Outdoor", "Decor"),
    "Nintendo Switch": ("Electronics", "Game Console"),
    "Nintendo Switch 2": ("Electronics", "Game Console"),
    "Nintendo Switch Lite": ("Electronics", "Game Console"),
    "astronaut suit": ("Decoration", "Suit"),
    "barbell": ("Outdoor", "Fitness"),
    "beekeeper's hive": ("Outdoor", "Hive"),
    "book": ("Decoration", "Book"),
    "bottled beverage": ("Kitchen", "Drink"),
    "bottled ship": ("Decoration", "Ship"),
    "castle gate": ("Outdoor", "Gate"),
    "claw-foot tub": ("Bathroom", "Bath"),
    # normalize leftover (broad=Chair/Storage/Instrument/Sofa/Umbrella) entries
    "golden seat": ("Furniture", "Seat"),
    "crew member's seat": ("Furniture", "Seat"),
    "transit seat": ("Furniture", "Seat"),
    "ruined seat": ("Furniture", "Seat"),
    "theremin": ("Decoration", "Instrument"),
    "recycled-can thumb piano": ("Decoration", "Instrument"),
    "nook umbrella": ("Umbrella", "Umbrella"),
    "festive parasol": ("Umbrella", "Parasol"),
    "festivale parasol": ("Umbrella", "Parasol"),
    "parasol": ("Umbrella", "Parasol"),
    "cinnamoroll parasol": ("Umbrella", "Parasol"),
    "umbrella stand": ("Furniture", "Storage"),
    "golden seat": ("Furniture", "Seat"),
})



# (keywords, (broad, specific)) — first substring match on the lowercased name wins.
KEYWORD_RULES = [
    # Seating
    (("chair", "seat"), ("Furniture", "Chair")),
    (("stool",), ("Furniture", "Stool")),
    (("bench",), ("Furniture", "Bench")),
    (("sofa", "couch", "loveseat", "lounge", "chaise"), ("Furniture", "Sofa")),
    # Tables / desks
    (("table", "kotatsu", "billiard", "podium"), ("Furniture", "Table")),
    (("desk",), ("Furniture", "Desk")),
    (("vanity",), ("Furniture", "Vanity")),
    # Beds
    (("bed", "hammock", "futon", "cot", "crib", "sleeping bag", "couch bed"), ("Furniture", "Bed")),
    # Storage
    (("wardrobe", "dresser", "chest", "cabinet", "closet", "locker", "safe", "drawer",
      "shelf", "stand", "trophy case", "record box", "box", "display case",
      "organizer", "rack", "shed", "storage"), ("Furniture", "Storage")),
    # Kitchen broad
    (("stove", "oven", "fridge", "refrigerator", "freezer", "toaster", "microwave",
      "espresso", "coffee", "mixer", "blender", "dishwasher", "cooker", "rice cooker",
      "juicer", "kettle"), ("Kitchen", "Appliance")),
    (("pot", "pan", "skillet", "frying", "cookware", "cutting board", "bakeware"), ("Kitchen", "Cookware")),
    (("counter", "island", "kitchen", "system", "sink", "register", "cash", "cart", "serving"), ("Kitchen", "Kitchenware")),
    (("cup", "mug", "glass", "pitcher", "tray"), ("Kitchen", "Cup")),
    (("food", "dish", "meal"), ("Kitchen", "Food")),
    # Bathroom
    (("bathroom", "bath", "shower", "toilet", "bidet", "towel", "soap", "sink",
      "washbasin", "washtub"), ("Bathroom", "Bathroom")),
    # Lighting
    (("lamp", "lantern", "candle", "light", "torch", "chandelier", "uplight", "bulb",
      "spotlight", "ceiling fan", "festival lantern"), ("Lighting", "Lamp")),
    # Plants
    (("plant", "bonsai", "cactus", "potted", "flower", "bush", "shrub", "topiary",
      "tree", "bamboo shoot", "monstera", "palm", "lily", "rose", "tulip", "windflower",
      "hyacinth", "cosmos", "sunflower", "mum", "pansy", "wisteria", "azalea",
      "hydrangea", "grass", "fern", "ivy", "coconut"), ("Plant", "Plant")),
    # Instruments (under Decoration: a guitar is a decoration, specifically a guitar)
    (("guitar", "piano", "drum", "violin", "kazoo", "marimba", "saxophone", "trumpet",
      "cello", "harp", "ukulele", "sitar", "flute", "bongo", "conga", "synthesizer",
      "tuba", "mic", "gong", "pipa", "clarinet", "keyboard", "organ", "theremin",
      "busking", "recycled-can"), ("Decoration", "Instrument")),
    # Electronics
    (("tv", "television", "stereo", "radio", "computer", "laptop", "phone", "console",
      "screen", "monitor", "camera", "amplifier", "dj", "turntable", "record player",
      "speaker", "jukebox", "server", "fan", "heater", "air conditioner", "robot",
      "amp", "tape recorder", "projector", "music player", "machine"), ("Electronics", "Electronics")),
    # Clocks
    (("clock",), ("Furniture", "Clock")),
    # Toys / games
    (("toy", "doll", "plush", "bear", "panda", "game", "ball", "block", "train",
      "car", "rocket", "arcade", "pinball", "skateboard", "tricycle", "kart",
      "scooter", "bike", "hula hoop", "go board", "chess", "foosball", "puzzle",
      "dice", "tent", "sandbox", "sand castle", "dollhouse", "slide", "seesaw",
      "playground", "springy", "stroller", "tricycle"), ("Toy", "Toy")),
    # Pets / animals
    (("tank", "cage", "bird", "hamster", "fish", "aquarium", "pet", "turtle", "cricket",
      "emu", "ant", "bug", "frog", "aquarium"), ("Pet", "Pet")),
    # Containers
    (("basket", "crate", "bucket", "barrel", "hamper", "trash", "bin", "bag",
      "cart", "cooler", "lunch", "picnic", "pot", "canister", "jar", "case",
      "briefcase", "suitcase", "waste"), ("Container", "Container")),
    # Sculptures / art
    (("statue", "sculpture", "urn", "bust", "monument", "pyramid", "skeleton",
      "trophy", "model", "figure", "head", "llama", "rocket", "figurine"), ("Decoration", "Figurine")),
    # Wall decor
    (("wall", "hanging", "mirror", "frame", "poster", "flag", "sign", "garland",
      "scroll", "tapestry", "plate", "wreath", "pennant", "panel", "partition",
      "screen", "chalkboard", "board", "print", "banner", "curtain", "map",
      "mounted", "swag", "sconce"), ("Wall Decor", "Wall Decor")),
    # Ceiling decor
    (("mobile", "chandelier", "ceiling", "balloon", "festive lights", "party lights"), ("Ceiling Decor", "Ceiling Decor")),
    # Outdoor / garden
    (("garden", "fence", "arch", "fountain", "birdbath", "standee", "gnome", "solar",
      "outdoor", "pool", "beach", "umbrella", "yard", "campfire", "picnic",
      "barbecue", "grill", "water pump", "well", "rock", "stone", "sports",
      "goal", "fitness", "exercise", "treadmill", "weight", "punching"), ("Outdoor", "Outdoor")),
    # Rugs
    (("rug", "carpet", "mat", "tatami", "floor"), ("Rug", "Rug")),
    # Pillars / structures
    (("pillar", "column", "arch"), ("Furniture", "Pillar")),
    # Kitchen food / drink / ware (re-added after rule split)
    (("soup", "curry", "pie", "cake", "jam", "bread", "pizza", "salad", "ramen",
      "cookie", "candy", "food", "meal", "dish", "snack", "scone", "crepe", "pudding",
      "jelly", "smoothie", "fried", "stew", "noodles", "rice", "porridge", "quiche",
      "sandwich", "tart", "pasta", "gnocchi", "risotto", "pilaf", "biryani", "omurice",
      "sushi", "curry", "potato", "zongzi", "songpyeon", "tangyuan", "dango",
      "bento", "chowder", "pancake", "waffle", "toast", "bagel", "donut", "cake"),
     ("Kitchen", "Food")),
    (("juice", "soda", "milk", "smoothie", "latte", "shake", "drink", "water",
      "tea", "coffee"), ("Kitchen", "Drink")),
    (("cup", "mug", "glass", "pitcher", "teacup", "tumbler"), ("Kitchen", "Cups")),
    (("plate", "bowl", "dish", "dinnerware", "cutlery", "fork", "spoon", "chopsticks",
      "knife block", "spice rack"), ("Kitchen", "Plates")),
]

def classify(name):
    """Return the category path (1-3 levels) for an item name.

    e.g. ('Kitchen','Appliance','Fridge') or ('Decoration','Instrument','Guitar').
    The tree is implicit: an item inherits every ancestor, so selecting
    'Kitchen' includes 'Kitchen/Appliance', 'Kitchen/Cups', etc.
    """
    key = name.strip().lower()
    if key in OVERRIDES:
        path = list(OVERRIDES[key])
    else:
        path = None
        for keywords, t in KEYWORD_RULES:
            if any(k in key for k in keywords):
                path = list(t)
                break
        if path is None:
            return ("Other", "Other")
    # 3rd level: refine by keyword when the parent allows it.
    parent = tuple(path)
    if parent in THIRD:
        for kw, leaf in THIRD[parent].items():
            if kw in key:
                return (*path, leaf)
    return tuple(path)

def type_for(name):
    """Backward-compat: top-level category only."""
    return classify(name)[0]

OVERRIDES = {k.lower(): v for k, v in OVERRIDES.items()}
# (parent-path, {keyword: 3rd-level leaf}) — refines items whose 2nd level matches.
THIRD = {
    ("Kitchen", "Appliance"): {
        "fridge": "Fridge", "refrigerator": "Fridge", "freezer": "Freezer",
        "stove": "Stove", "oven": "Oven", "microwave": "Microwave",
        "toaster": "Toaster", "dishwasher": "Dishwasher", "mixer": "Mixer",
        "blender": "Blender", "cooker": "Cooker", "rice cooker": "Rice Cooker",
        "espresso": "Espresso Machine", "coffee": "Coffee Machine", "juicer": "Juicer",
    },
    ("Decoration", "Instrument"): {
        "guitar": "Guitar", "piano": "Piano", "drum": "Drums", "violin": "Violin",
        "clarinet": "Clarinet", "saxophone": "Saxophone", "trumpet": "Trumpet",
        "cello": "Cello", "harp": "Harp", "ukulele": "Ukulele", "sitar": "Sitar",
        "flute": "Flute", "bongo": "Bongos", "conga": "Congas", "marimba": "Marimba",
        "kazoo": "Kazoo", "tuba": "Tuba", "gong": "Gong", "pipa": "Pipa",
        "keyboard": "Keyboard", "synthesizer": "Synthesizer", "theremin": "Theremin",
        "mic": "Microphone", "organ": "Organ", "busking": "Instrument",
    },
}

if __name__ == "__main__":
    import os, sys
    sys.path.insert(0, os.path.dirname(__file__))
    import build_db
    z, sheets = build_db.load_workbook()
    z.close()
    names = set()
    for s in FURNITURE_CATEGORIES:
        hdr = sheets[s][0]
        idx = {h: i for i, h in enumerate(hdr) if h}
        name_i = idx.get("Name", 0)
        for r in sheets[s][1:]:
            if r and name_i < len(r) and r[name_i]:
                names.add(r[name_i].strip())
    rows = sorted((n, classify(n)) for n in names)
    os.makedirs("res", exist_ok=True)
    with open("res/furniture_types.tsv", "w") as f:
        f.write("name\tpath\n")
        for n, path in rows:
            f.write(f"{n}\t{'/'.join(path)}\n")
    from collections import Counter
    tops = Counter(p[0] for _, p in rows)
    print(f"cataloged {len(rows)} items")
    print("\ntop-level categories:")
    for t, n in tops.most_common():
        print(f"  {t:14s} {n}")
    print("\nsample 3rd-level paths:")
    seen = set()
    for _, p in rows:
        if len(p) >= 3 and p[:2] not in seen:
            seen.add(p[:2])
            print("  ", "/".join(p))
    others = [n for n, p in rows if p[0] == "Other"]
    print(f"\nunclassified ({len(others)}):")
    for n in others:
        print("  ", n)
